### ISSUE TITLE
Commercial paper demo crashing following restart

### ISSUE THREAD

**Issue by bravera** [IBM-Blockchain/ibm-blockchain-issues#51] opened 2016-10-05 11:27 UTC
I deployed a fresh CP demo today and was able to create users, log in as a couple of them and create paper and make a trade. Then I tried to log in as the auditor and put in the wrong password (which the README says doesnt matter), and it would not let me log in. I then put in the correct password and it still would not let me in. I then returned to the other users and tried them - none could log in anymore.
Next I restarted the app and now it will not stay up at all. It crashes immediately.
I attach the output of cf logs below....any ideas?

2016-10-05T12:24:20.57+0100 [DEA/98]     OUT Starting app instance (index 0) with guid 9d4df5fd-5330-43c1-8bf1-9531077e72e1
2016-10-05T12:24:30.78+0100 [App/0]      ERR Warning: connect.session() MemoryStore is not
2016-10-05T12:24:30.78+0100 [App/0]      ERR designed for a production environment, as it will leak
2016-10-05T12:24:30.78+0100 [App/0]      ERR memory, and will not scale past a single process.
2016-10-05T12:24:30.89+0100 [App/0]      OUT ------------------------------------------ Server Up - 0.0.0.0:61369 ------------------------------------------
2016-10-05T12:24:30.89+0100 [App/0]      OUT Running using Developer settings
2016-10-05T12:24:30.89+0100 [App/0]      OUT - Tracking Deployment
2016-10-05T12:24:31.28+0100 [App/0]      ERR I1005 11:24:31.282581398      29 ev_epoll_linux.c:84]        epoll engine will be using signal: 36
2016-10-05T12:24:31.28+0100 [App/0]      ERR D1005 11:24:31.282777825      29 ev_posix.c:106]             Using polling engine: epoll
2016-10-05T12:24:31.70+0100 [App/0]      OUT loading hardcoded peers
2016-10-05T12:24:31.70+0100 [App/0]      OUT loading hardcoded users
2016-10-05T12:24:31.70+0100 [App/0]      OUT overwritting peers, loading from a vcap service:  ibm-blockchain-5-prod
2016-10-05T12:24:31.70+0100 [App/0]      OUT overwritting ca, loading from a vcap service:  ibm-blockchain-5-prod
2016-10-05T12:24:31.70+0100 [App/0]      OUT overwritting users, loading from a vcap service:  ibm-blockchain-5-prod
2016-10-05T12:24:31.70+0100 [App/0]      OUT calling network config
2016-10-05T12:24:31.70+0100 [App/0]      OUT found cert us.blockchain.ibm.com
2016-10-05T12:24:31.87+0100 [App/0]      OUT Successfully got WebAppAdmin member ---> 
2016-10-05T12:24:32.66+0100 [App/0]      OUT Uploaded stats { ok: true }
2016-10-05T12:24:32.64+0100 [App/0]      OUT Uploaded stats { ok: true }
2016-10-05T12:24:32.68+0100 [App/0]      OUT Failed to enroll WebAppAdmin member  ---> Error: Identity or token does not match.
2016-10-05T12:24:32.69+0100 [App/0]      ERR       throw Error('Uncaught, unspecified "error" event.');
2016-10-05T12:24:32.69+0100 [App/0]      ERR             ^
2016-10-05T12:24:32.69+0100 [App/0]      ERR Error: Uncaught, unspecified "error" event.
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at Error (native)
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at TransactionContext.emit (events.js:87:13)
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at /home/vcap/app/node_modules/hfc/lib/hfc.js:932:22
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at /home/vcap/app/node_modules/hfc/lib/hfc.js:1062:24
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at Member.getNextTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:812:20)
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at TransactionContext.getMyTCert (/home/vcap/app/node_modules/hfc/lib/hfc.js:1060:21)
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at TransactionContext.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:929:14)
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at Member.deploy (/home/vcap/app/node_modules/hfc/lib/hfc.js:765:12)
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at deploy (/home/vcap/app/app.js:289:32)
2016-10-05T12:24:32.69+0100 [App/0]      ERR     at /home/vcap/app/app.js:275:17
2016-10-05T12:24:32.83+0100 [API/3]      OUT App instance exited with guid 9d4df5fd-5330-43c1-8bf1-9531077e72e1 payload: {"cc_partition"=>"default", "droplet"=>"9d4df5fd-5330-43c1-8bf1-9531077e72e1", "version"=>"2140468f-ba39-4b7e-afb2-057d72ab707e", "instance"=>"e5d496834974447280d2f797ac340e23", "index"=>0, "reason"=>"CRASHED", "exit_status"=>1, "exit_description"=>"app instance exited", "crash_timestamp"=>1475666672}
2016-10-05T12:24:32.69+0100 [App/0]      ERR events.js:87

**Comment by masterDev1985** [comment] 2016-10-05 18:26
I suspect there was a connection issue between the application and the peers it was trying to interact with.  We had to restart some of the machines hosting the Bluemix service last night.  It's likely that one or more of the peers in your network was affected.  Could you try to restart the app again and see if the issue is resolved?

**Comment by bravera** [comment] 2016-10-17 14:07
Didnt help.
I have now deleted it and several times tried to deploy a new version.
Each time the app crashes on start up without ever getting to a UI.
The Blockchain console is not showing any problems.
My latest network ID is 2a128aa8ff37414a96718c455c30b03e

**Comment by masterDev1985** [comment] 2016-10-18 13:53
@bravera I've been able to duplicate your error on my end.  It seems that the version of the `hfc` module that CP uses does not play well with the new networks that we have made available on Bluemix.  I'm working on a fix. ;)

**Comment by jay242526** [comment] 2017-01-05 09:47
Hello,
I deploy the commercial paper demo app to bluemix from https://github.com/IBM-Blockchain/cp-web#readme
And get same error when starting. 
The cf log is below:
2017-01-05T17:15:28.67+0800 [CELL/0]     OUT Creating container
2017-01-05T17:15:33.62+0800 [CELL/0]     OUT Successfully created container
2017-01-05T17:15:38.11+0800 [CELL/0]     OUT Starting health monitoring of container
2017-01-05T17:15:38.72+0800 [APP/0]      OUT SETUP.JS: Assuming this app is running on localhost.
2017-01-05T17:15:38.72+0800 [APP/0]      OUT app.js: Configuring Express app
2017-01-05T17:15:39.00+0800 [APP/0]      OUT app.js: Staring http server on: localhost:3000
2017-01-05T17:15:39.00+0800 [APP/0]      ERR Warning: connect.session() MemoryStore is not
2017-01-05T17:15:39.00+0800 [APP/0]      ERR designed for a production environment, as it will leak
2017-01-05T17:15:39.00+0800 [APP/0]      ERR memory, and will not scale past a single process.
2017-01-05T17:15:39.00+0800 [APP/0]      OUT app.js: ---- Tracking Deployment
2017-01-05T17:15:39.09+0800 [APP/0]      OUT app.js: Attempting to read hardcoded network credentials...
2017-01-05T17:15:39.09+0800 [APP/0]      OUT app.js: loading hardcoded users
2017-01-05T17:15:39.09+0800 [APP/0]      OUT overwritting peers, loading from a vcap service:  ibm-blockchain-5-prod
2017-01-05T17:15:39.09+0800 [APP/0]      OUT overwritting ca, loading from a vcap service:  ibm-blockchain-5-prod
2017-01-05T17:15:39.09+0800 [APP/0]      OUT overwritting users, loading from a vcap service:  ibm-blockchain-5-prod
2017-01-05T17:15:39.58+0800 [APP/0]      OUT chain_setup.js setting up chain object
2017-01-05T17:15:39.58+0800 [APP/0]      OUT chain_setup.js creating keyValStore in: /home/vcap/app/keyValStore
2017-01-05T17:15:39.58+0800 [APP/0]      OUT chain_setup.js configuring the blockchain network
2017-01-05T17:15:39.58+0800 [APP/0]      OUT chain_setup.js Setting membership service url: grpcs://3931e421ba8b49f38e0bf0f190b728d8-ca.us.blockchain.ibm.com:30002
2017-01-05T17:15:39.58+0800 [APP/0]      OUT chain_setup.js Using certificate for membership service connection
2017-01-05T17:15:39.58+0800 [APP/0]      OUT chain_setup.js certificate being used: <Buffer 2d 2d 2d 2d 2d 42 45 47 49 4e 20 43 45 52 54 49 46 49 43 41 54 45 2d 2d 2d 2d 2d 0d 0a 4d 49 49 44 36 54 43 43 41 32 36 67 41 77 49 42 41 67 49 51 43 ... >
2017-01-05T17:15:39.68+0800 [APP/0]      OUT chain_setup.js setting peer urls: [ 'grpcs://3931e421ba8b49f38e0bf0f190b728d8-vp0.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.68+0800 [APP/0]      OUT   'grpcs://3931e421ba8b49f38e0bf0f190b728d8-vp1.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.68+0800 [APP/0]      OUT   'grpcs://3931e421ba8b49f38e0bf0f190b728d8-vp2.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.68+0800 [APP/0]      OUT chain_setup.js using certificate for peer connections
2017-01-05T17:15:39.69+0800 [APP/0]      OUT chain_setup.js Debug: Membership service: MemberServicesImpl {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   ecaaClient: Client { '$channel': Channel {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   ecapClient: Client { '$channel': Channel {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   tcapClient: Client { '$channel': Channel {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   tlscapClient: Client { '$channel': Channel {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   cryptoPrimitives: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT    Crypto {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      hashAlgorithm: 'SHA3',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      securityLevel: 256,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      suite: 'sha3-256',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      curveName: 'secp256r1',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      hashFunction: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT       { [Function]
2017-01-05T17:15:39.69+0800 [APP/0]      OUT         create: [Function],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT         hex: [Function],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT         buffer: [Function],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT         array: [Function] },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      hashFunctionKeyDerivation: { [Function: hash_sha3_256] hash: [Function] },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      hashOutputSize: 32,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      ecdsaCurve: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT       PresetCurve {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT         g: <EC Point x: 6b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c296 y: 4fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5>,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT         n: <BN: ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc632551>,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT         hash: [Object] } } }
2017-01-05T17:15:39.69+0800 [APP/0]      OUT chain_setup.js Debug: Peers: [ Peer {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     sendTransaction: [Function],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     url: 'grpcs://3931e421ba8b49f38e0bf0f190b728d8-vp0.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     chain: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      Chain {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        peers: [Circular],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        securityEnabled: true,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        members: {},
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        tcertBatchSize: 200,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        devMode: false,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        preFetchMode: true,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        deployWaitTime: 80,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        invokeWaitTime: 5,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        name: 'cp_chaincode',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        eventHub: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        keyValStore: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        memberServices: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        cryptoPrimitives: [Object] },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     ep: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      Endpoint {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        addr: '3931e421ba8b49f38e0bf0f190b728d8-vp0.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        creds: ChannelCredentials {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     peerClient: Client { '$channel': Channel {} } },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   Peer {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     sendTransaction: [Function],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     url: 'grpcs://3931e421ba8b49f38e0bf0f190b728d8-vp1.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     chain: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      Chain {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        peers: [Circular],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        securityEnabled: true,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        members: {},
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        tcertBatchSize: 200,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        devMode: false,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        preFetchMode: true,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        deployWaitTime: 80,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        invokeWaitTime: 5,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        name: 'cp_chaincode',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        eventHub: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        keyValStore: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        memberServices: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        cryptoPrimitives: [Object] },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     ep: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        addr: '3931e421ba8b49f38e0bf0f190b728d8-vp1.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        creds: ChannelCredentials {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     peerClient: Client { '$channel': Channel {} } },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   Peer {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     sendTransaction: [Function],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     url: 'grpcs://3931e421ba8b49f38e0bf0f190b728d8-vp2.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     chain: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      Chain {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        peers: [Circular],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        securityEnabled: true,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        members: {},
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        tcertBatchSize: 200,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        invokeWaitTime: 5,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        name: 'cp_chaincode',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        eventHub: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        keyValStore: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        memberServices: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        cryptoPrimitives: [Object] },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     ep: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      Endpoint {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        addr: '3931e421ba8b49f38e0bf0f190b728d8-vp2.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        creds: ChannelCredentials {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT   Peer {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     sendTransaction: [Function],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     chain: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      Chain {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        peers: [Circular],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        securityEnabled: true,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        members: {},
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        tcertBatchSize: 200,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        devMode: false,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        preFetchMode: true,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        deployWaitTime: 80,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        invokeWaitTime: 5,
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        name: 'cp_chaincode',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        eventHub: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        keyValStore: [Object],
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        cryptoPrimitives: [Object] },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     ep: 
2017-01-05T17:15:39.69+0800 [APP/0]      OUT      Endpoint {
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        addr: '3931e421ba8b49f38e0bf0f190b728d8-vp3.us.blockchain.ibm.com:30002',
2017-01-05T17:15:39.69+0800 [APP/0]      OUT        creds: ChannelCredentials {} },
2017-01-05T17:15:39.69+0800 [APP/0]      OUT     peerClient: Client { '$channel': Channel {} } } ]
2017-01-05T17:15:39.69+0800 [APP/0]      OUT chain_setup.js Getting registrar: WebAppAdmin
2017-01-05T17:15:39.71+0800 [APP/0]      OUT app.js: Server Up - localhost:3000
2017-01-05T17:15:39.72+0800 [APP/0]      OUT chain_setup.js successfully got registrar. Enrolling with secret: 09fb19884e
2017-01-05T17:15:39.89+0800 [APP/0]      ERR chain_setup.js failed to enroll registrar: Identity or token does not match.
2017-01-05T17:15:39.89+0800 [APP/0]      ERR chain_setup.js couldn't configure the network
2017-01-05T17:15:39.89+0800 [APP/0]      OUT app.js: Chain setup failed: { Error: Identity or token does not match.
2017-01-05T17:15:39.89+0800 [APP/0]      OUT     at /home/vcap/app/node_modules/grpc/src/node/src/client.js:417:17 code: 2, metadata: Metadata { _internal_repr: {} } }
2017-01-05T17:15:39.89+0800 [APP/0]      ERR /home/vcap/app/app.js:225
2017-01-05T17:15:39.89+0800 [APP/0]      ERR             throw error;
2017-01-05T17:15:39.89+0800 [APP/0]      ERR             ^
2017-01-05T17:15:39.89+0800 [APP/0]      ERR Error: Identity or token does not match.
2017-01-05T17:15:39.89+0800 [APP/0]      ERR     at /home/vcap/app/node_modules/grpc/src/node/src/client.js:417:17
2017-01-05T17:15:39.90+0800 [APP/0]      OUT Exit status 1
2017-01-05T17:15:39.95+0800 [CELL/0]     OUT Exit status 0
2017-01-05T17:15:40.01+0800 [API/2]      OUT App instance exited with guid 1075b695-ba4d-4ead-8b33-37907af342ba payload: {"instance"=>"", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 1\n* cancelled\n* cancelled", "crash_count"=>7, "crash_timestamp"=>1483607739965260629, "version"=>"33e5306b-0e54-4999-9539-449e8ec804b4"}
2017-01-05T17:15:41.22+0800 [CELL/0]     OUT Successfully destroyed container

**Comment by mrshah-at-work** [comment] 2017-01-05 10:38
```
2017-01-05T17:15:38.72+0800 [APP/0] OUT SETUP.JS: Assuming this app is running on localhost.
2017-01-05T17:15:38.72+0800 [APP/0] OUT app.js: Configuring Express app
2017-01-05T17:15:39.00+0800 [APP/0] OUT app.js: Staring http server on: localhost:3000
```

The app thinks it is *not* running on bluemix. This might be due to a recent change in the way bluemix's *host* and *port* are provided to the app, we will fix this. Thanks @bravera

**Comment by jay242526** [comment] 2017-01-05 11:23
Hello Mihir Shah,
Thanks your quickly response.
Wait your fix.
:)

**Comment by mrshah-at-work** [comment] 2017-01-05 11:55
https://github.com/IBM-Blockchain/cp-web/pull/66 should fix it.

**Comment by jay242526** [comment] 2017-01-05 15:38
Hello Mihir Shah,

Just test the latest version.
It's already fixed.
Thanks a lot.

**Comment by mrshah-at-work** [comment] 2017-01-05 15:44
Sorry @jay242526, I meant to thank you in my previous comment. 

I will close this issue as the demo is working on bluemix.

**Closed as completed by mrshah-at-work** 2017-01-05 15:44 UTC
