### ISSUE TITLE
Discovery server is down

### ISSUE THREAD

**Issue by sriefx143** [IBM-Blockchain/ibm-blockchain-issues#4] opened 2016-07-18 15:25 UTC
My server is not coming up.  Unable to reach the APIs

**Comment by sriefx143** [comment] 2016-07-18 15:34
+ another error: The page will not load with message "internal server error"

**Comment by sriefx143** [comment] 2016-07-18 17:27
server is up  - another problem

{
  "jsonrpc": "2.0",
  "error": {
    "code": -32003,
    "message": "Query failure",
    "data": "Error when querying chaincode: Error:Failed to launch chaincode spec(Timeout expired while starting chaincode aec0e.....))"
  },
  "id": 0
}

**Comment by mastersingh24** [comment] 2016-07-19 08:38
@sriefx143 - have you tried things again recently?  we had some network issues which should be resolved

**Comment by sriefx143** [comment] 2016-07-19 13:08
yes, just tried it now 9:07 AM Tuesday.  My Validating Peer is not starting.  Status is stopped, tried to restart multiple times - it wouldnt come up.

**Comment by mastersingh24** [comment] 2016-07-19 13:30
when did you create this network?  Is it a 2 peer network?

**Comment by sriefx143** [comment] 2016-07-19 13:47
@mastersingh24 
I created it two months back.  I have few test apps that I have been working on and testing.
Yes, it is .

**Comment by sriefx143** [comment] 2016-07-20 14:31
@mastersingh24 
any updates?  the server briefly came back up last night but down again - very flaky!!!

Log messsage:

ERR - 2016/07/20 05:04:02 transport: http2Client.notifyError got notified that the client transport was broken EOF.
ERR - 2016/07/20 05:04:02 Received error from server: rpc error: code = 13 desc = "transport is closing", ending chaincode stream
OUT - Error starting Simple chaincode: rpc error: code = 13 desc = "transport is closing"

**Comment by mastersingh24** [comment] 2016-08-15 17:02
I am closing this as we know there are problems with 2 peer networks but now that we can create new service instances with 4  peer networks we are not worrying about the 2 peer networks

**Closed by mastersingh24** 2016-08-15 17:02 UTC

**Comment by janips** [comment] 2017-11-29 12:03
I am having 2 peers and facing the same issue. The issue is resolved or its still there? 
I know, am asking after a long time but will give me an idea about it.
