### ISSUE TITLE
Can anyone help me with code for trasferring an event in JSON onto my blockchain?

### ISSUE THREAD

**Issue by suffiasameera** [IBM-Blockchain/ibm-blockchain-issues#107] opened 2017-04-27 13:55 UTC
How do I transfer the event received from github onto my blockchain using REST apis? Please help me with the code for directly invoking the REST apis on my blockchain.

Thanks!

**Comment by dshuffma-ibm** [comment] 2017-05-24 13:45
duplicate of https://github.com/IBM-Blockchain/ibm-blockchain-js/issues/35

**Closed as completed by dshuffma-ibm** 2017-05-24 13:45 UTC
